#!/usr/bin/env python3
"""Render the StructIRES native-classifier LaTex rows from a verified aggregate."""
from __future__ import annotations

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = Path("/9950backfile/lant/data/ires-design-external-runs/") / \
    "structires_native_authorstyle_batchshuffle_multifold_0_2_4_v2_20260823/aggregate_metrics.csv"
DEFAULT_OUTPUT = ROOT / "paper" / "bibe2026" / "tables" / "recognition_native_rows.tex"


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--protocol-label", default=None,
                        help="Optional complete LaTex protocol cell; defaults to '<n>-fold validation-clean native folds'.")
    return parser.parse_args()


def value(row: dict[str, str], key: str) -> float:
    try:
        return float(row[key])
    except (KeyError, ValueError) as exc:
        raise ValueError(f"missing numeric {key}") from exc


def metric(row: dict[str, str], name: str) -> str:
    return f"${value(row, name + '_mean'):.3f}\\pm{value(row, name + '_std'):.3f}$"


def main() -> int:
    args = arguments()
    with args.input.open(encoding="utf-8", newline="") as handle:
        rows = {row["model"]: row for row in csv.DictReader(handle)}
    expected = {"author_style_sequence_only", "structires_mfe_contact_fusion"}
    if set(rows) != expected:
        raise ValueError(f"unexpected model rows: {sorted(rows)}")
    n_folds = int(value(rows["author_style_sequence_only"], "n_folds"))
    if int(value(rows["structires_mfe_contact_fusion"], "n_folds")) != n_folds:
        raise ValueError("unmatched fold counts")
    protocol = args.protocol_label or f"{n_folds}-fold validation-clean native folds"
    rendered = [
        "%% Generated by scripts/render_native_classifier_rows.py from independently verified aggregate_metrics.csv.",
        "%% Do not hand-edit numerical values; rerun after updating the immutable multifold summary.",
        "\\newcommand{\\StructIRESNativeRows}{%",
        "RNA-FM sequence-only re-train & public RNA-FM & Matched local re-train & "
        f"{protocol} & {metric(rows['author_style_sequence_only'], 'auc')} & "
        f"{metric(rows['author_style_sequence_only'], 'aupr')} & {metric(rows['author_style_sequence_only'], 'f1')} \\\\",
        "\\textsc{StructIRES-Classifier} & RNA-FM + MFE contacts & Matched local re-train & "
        f"{protocol} & {metric(rows['structires_mfe_contact_fusion'], 'auc')} & "
        f"{metric(rows['structires_mfe_contact_fusion'], 'aupr')} & {metric(rows['structires_mfe_contact_fusion'], 'f1')} \\\\",
        "}",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(rendered) + "\n", encoding="utf-8")
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
